### PR TITLE
Upgrade to Intellij platform gradle plugin 2.0

### PR DESCRIPTION
**Pull request by peddiashrith**
Upgrade to Intellij platform gradle plugin 2.0

1. This upgrade is required in order to support Intellij 2024.2+ (242+) in future - [ref comment](https://youtrack.jetbrains.com/issue/KTIJ-30554/org.gradle.tooling.BuildException-Cannot-find-builtin-plugin-org.jetbrains.kotlin-for-IDE#focus=Comments-27-10110900.0-0)
2. Upgrade gradle to 8.10 version
3. Bump version to `2.7.1`
4. Remove support for `2022.2` in favour of `2024.2` as the minimal supported version by new intellij platform plugin is `2022.3`

### References
- Migration to gradle 2.0 - https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-migration.html
- Gradle 2.0 - https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html
- https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-dependencies-extension.html
- https://plugins.jetbrains.com/docs/intellij/plugin-dependencies.html

### Testing
- `./gradlew buildPlugin`
- `./gradlew verifyPlugin`
- Tested that generated zip file is working with IntelliJ `2024.1` version

### CODE REVIEW

**Comment by popematt** [comment]
It looks like the workflows are failing because we're using an outdate version of the upload-artifact action. I don't want to clob too many changes together in one PR, so I'll see about updating the GitHub action. Then, I think it would be a good idea to update to the IntelliJ platform Gradle plugin 2.0 in one PR (this one?), and then add support for 2024.2 in a separate PR.

**Comment by peddiashrith** [comment]
Sure, will do

**Comment by popematt** [comment]
I've fixed the GitHub Action and merged the fix into your PR. Now the workflow is failing because of this error, which looks related to the Intellij platform gradle plugin update.

> FAILURE: Build failed with an exception.
>
> * Where:
> Build file '/home/runner/work/ion-intellij-plugin/ion-intellij-plugin/build.gradle.kts' line: 247
>
> * What went wrong:
> Collection contains no element matching the predicate.

**Comment by peddiashrith** [comment]
I have updated the PR to include only changes related to upgrading to Intellij platform gradle plugin 2.0

**Comment by peddiashrith** [comment]
The workflows are failing becuase `PRODUCT_NAME` environment variable is being passed as `IC-2024.1` whereas the code is expecting just `2024.1` after my changes.

Do you suggest to change the code to hard code the prefix OR update envirnonment variable value to `2024.1` ?

**Comment by popematt** [comment]
> Do you suggest to change the code to hard code the prefix = IC- OR update envirnonment variable value to 2024.1 ?

I don't have a preference either way, as long as it works. If/when we support other IntelliJ IDEs, we can revisit if we need to.

**Comment by peddiashrith** [comment]
Pushed a commit to fix the workflow failure, please trigger it as I am unable to trigger

**Comment by peddiashrith** [comment]
Now it is failing due to below error where the minimal supported intellij platform is `2022.3` by new intellij platform plugin. 

Question: Can we remove build for `2022.2` version in order to support `2024.2`?

```
[org.jetbrains.intellij.platform] The following plugin configuration issues were found:
- The minimal supported IntelliJ Platform version is `2022.3` (branch `223`), current: '2022.2' ('222.3345.118')
```

**Comment by peddiashrith** [comment]
Removed support for `2022.2`

**Comment by popematt** [comment]
```
Task :compileTestKotlin FAILED
e: file:///home/runner/work/ion-intellij-plugin/ion-intellij-plugin/src/test/kotlin/com/amazon/ion/plugin/intellij/formatting/IonBasicFormattingTest.kt:8:5 'getBasePath' overrides nothing
e: file:///home/runner/work/ion-intellij-plugin/ion-intellij-plugin/src/test/kotlin/com/amazon/ion/plugin/intellij/formatting/IonBasicFormattingTest.kt:14:43 Unresolved reference: doTest
e: file:///home/runner/work/ion-intellij-plugin/ion-intellij-plugin/src/test/kotlin/com/amazon/ion/plugin/intellij/formatting/IonFormatterTestBase.kt:4:35 Unresolved reference: FormatterTestCase
e: file:///home/runner/work/ion-intellij-plugin/ion-intellij-plugin/src/test/kotlin/com/amazon/ion/plugin/intellij/formatting/IonFormatterTestBase.kt:7:39 Unresolved reference: FormatterTestCase
...
```

I'm not sure of the root cause for this failure. If I had to guess, I'd say there's a misconfiguration of the classpath or there was some breaking API change from IntelliJ. Were you able to successfully run `./gradlew build` locally with these changes? If so, then the problem could be some configuration in the `build-pr` workflow.

If you're able to figure it out, that's great, but if not, I'll also try to look into this more sometime in the next few days.

It seems like every fix is uncovering another issue, and I know that can be pretty discouraging sometimes. Thanks for being persistent and sticking with it this far!

**Review by popematt — APPROVED** [review]

**Comment by popematt** [comment]
As you may have noticed, I figured out the dependency issue, and I've merged the PR. Thanks for all your work on this!

**Comment by peddiashrith** [comment]
Thanks for fixing it!

Answering to your question: Both ./gradlew buildPlugin and ./gradlew verifyPlugin ran successfully locally in my machine. I wonder why

**Pull request merged**
